In [1]:
import numpy as np
import pandas as pd
import keras 
import os
import cv2
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten

Using TensorFlow backend.


In [2]:
import matplotlib.pyplot as plt
% matplotlib inline

In [3]:
train_img_path=r"E:\backup\python_image_classification\images\train_set"
test_img_path=r"E:\backup\python_image_classification\images\test_set"

In [5]:
def read_img_train(path):
    label=[]
    data1=[]
    counter=0
    for file in os.listdir(path):
        image_data=cv2.imread(os.path.join(path,file), cv2.IMREAD_GRAYSCALE)
        image_data=cv2.resize(image_data,(150,150))
        if file.startswith("one"):
            label.append(1)
        elif file.startswith("two"):
            label.append(2)
        elif file.startswith("five"):
            label.append(0)
        try:
            data1.append(image_data/255)
        except:
            label=label[:len(label)-1]
        counter+=1
        if counter % 10==0:
            print (counter," image data retreived")
    return label,data1

In [6]:
label_train,data_train=read_img_train(train_img_path)

10  image data retreived
20  image data retreived
30  image data retreived
40  image data retreived
50  image data retreived
60  image data retreived
70  image data retreived
80  image data retreived
90  image data retreived
100  image data retreived


In [7]:
def read_img_test(test_img_path):
    test_data=[]
    label=[]
    counter=0
    for file in os.listdir(test_img_path):
        image_data=cv2.imread(os.path.join(test_img_path,file), cv2.IMREAD_GRAYSCALE)
        try:
            image_data=cv2.resize(image_data,(150,150))
            test_data.append(image_data/255)
            if file.startswith("one"):
                label.append(1)
            elif file.startswith("two"):
                label.append(2)
            elif file.startswith("five"):
                label.append(0)
        except:
            print ("ek gaya")
        counter+=1
        if counter%4==0:
            print (counter," image data retreived")
    return label,test_data

In [8]:
label_test,data_test=read_img_test(test_img_path)

4  image data retreived
8  image data retreived
12  image data retreived


In [9]:
label_test

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2]

In [10]:
def createModel():
    model=Sequential()
    model.add(Conv2D(kernel_size=(3,3),filters=32,input_shape=(150,150,1),activation="relu"))
    model.add(Conv2D(kernel_size=(3,3),filters=32,activation="relu",padding="same"))
    model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))
    model.add(Conv2D(kernel_size=(3,3),filters=64,activation="relu"))
    model.add(Conv2D(kernel_size=(5,5),filters=64,activation="relu"))
    model.add(MaxPooling2D(pool_size=(3,3),strides=(2,2)))
    model.add(Conv2D(kernel_size=(2,2),strides=(2,2),filters=32))
    model.add(Flatten())
    model.add(Dropout(0.3))
    model.add(Dense(512,activation="relu"))
    model.add(Dense(3,activation="softmax"))
    model.summary()
     
    return model

In [11]:
data_train=np.array(data_train)
print (data_train.shape)
data_train=data_train.reshape((data_train.shape)[0],(data_train.shape)[1],(data_train.shape)[2],1)
#data1=data1/255
label_train=np.array(label_train)
print (data_train.shape)
print (label_train.shape)
label_train

(103, 150, 150)
(103, 150, 150, 1)
(103,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
from keras.utils import to_categorical

In [13]:
one_hot_labels= to_categorical(label_train[0:])

In [14]:
one_hot_labels

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1

In [15]:
data_test=np.array(data_test)
print (data_test.shape)
data_test=data_test.reshape((data_test.shape)[0],(data_test.shape)[1],(data_test.shape)[2],1)

(15, 150, 150)


In [16]:
one_hot_labels_test= to_categorical(label_test[0:])

In [17]:
one_hot_labels_test

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

In [18]:
from keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(
        zoom_range=0.2, # randomly zoom into images
        rotation_range=10,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False)  # randomly flip images

In [20]:
model1 = createModel()
batch_size = 5
epochs = 100
model1.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
 
history = model1.fit_generator(datagen.flow(data_train,one_hot_labels, batch_size=batch_size),steps_per_epoch=int(np.ceil(data_train.shape[0] / float(batch_size))), epochs=epochs, verbose=1,validation_data=(data_test[:-1],one_hot_labels_test))
 
#model1.evaluate(data_test, label_test)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 148, 148, 32)      320       
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 148, 148, 32)      9248      
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 74, 74, 32)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 72, 72, 64)        18496     
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 68, 68, 64)        102464    
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 33, 33, 64)        0         
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 16, 16, 32)        8224      
__________

21/21 [==============================] - 19s 891ms/step - loss: 0.9907 - acc: 0.6291 - val_loss: 1.6584 - val_acc: 0.5000
Epoch 49/100
21/21 [==============================] - 19s 921ms/step - loss: 0.7791 - acc: 0.6222 - val_loss: 1.9262 - val_acc: 0.4286
Epoch 50/100
21/21 [==============================] - 20s 964ms/step - loss: 0.8093 - acc: 0.6222 - val_loss: 1.5211 - val_acc: 0.5000
Epoch 51/100
21/21 [==============================] - 21s 977ms/step - loss: 0.7497 - acc: 0.6412 - val_loss: 1.3126 - val_acc: 0.6429
Epoch 52/100
21/21 [==============================] - 21s 988ms/step - loss: 0.7953 - acc: 0.6664 - val_loss: 1.7029 - val_acc: 0.3571
Epoch 53/100
21/21 [==============================] - 20s 945ms/step - loss: 0.9528 - acc: 0.6412 - val_loss: 1.3117 - val_acc: 0.6429
Epoch 54/100
21/21 [==============================] - 19s 910ms/step - loss: 0.7277 - acc: 0.7522 - val_loss: 1.6256 - val_acc: 0.4286
Epoch 55/100
21/21 [==============================] - 18s 876ms/step

In [21]:
predicted_labels=model1.predict(data_test)

In [22]:
predicted_labels

array([[9.97460365e-01, 3.03123193e-06, 2.53660395e-03],
       [1.09691719e-05, 9.99987364e-01, 1.68595113e-06],
       [9.81412053e-01, 9.44703538e-03, 9.14096367e-03],
       [6.81283057e-01, 9.23058391e-03, 3.09486389e-01],
       [3.80084693e-01, 4.91115414e-02, 5.70803761e-01],
       [2.33788978e-19, 1.00000000e+00, 7.22401321e-20],
       [2.32178599e-01, 1.96924970e-01, 5.70896387e-01],
       [1.59996268e-12, 9.99840260e-01, 1.59673160e-04],
       [7.19417483e-02, 2.26500511e-01, 7.01557755e-01],
       [1.02943578e-03, 9.98970270e-01, 4.16565342e-07],
       [2.03113395e-05, 5.30929327e-08, 9.99979615e-01],
       [7.46733323e-02, 4.94920241e-04, 9.24831748e-01],
       [1.66111533e-02, 5.01122355e-01, 4.82266456e-01],
       [4.11030276e-09, 4.54326909e-07, 9.99999523e-01],
       [8.63138795e-01, 1.27868745e-02, 1.24074325e-01]], dtype=float32)

In [23]:
predicted_labels=np.round(predicted_labels,decimals=2)

In [24]:
predicted_labels

array([[1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.98, 0.01, 0.01],
       [0.68, 0.01, 0.31],
       [0.38, 0.05, 0.57],
       [0.  , 1.  , 0.  ],
       [0.23, 0.2 , 0.57],
       [0.  , 1.  , 0.  ],
       [0.07, 0.23, 0.7 ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.07, 0.  , 0.92],
       [0.02, 0.5 , 0.48],
       [0.  , 0.  , 1.  ],
       [0.86, 0.01, 0.12]], dtype=float32)

In [25]:
model1.evaluate(data_test[0:-1],one_hot_labels_test)

14/14 [==============================] - 1s 47ms/step


[1.193672776222229, 0.6428571343421936]

In [26]:
print(model1.metrics_names)

['loss', 'acc']
